In [ ]:
import pandas as pd

## 1: Big Cities Health Data Inventory

In [ ]:
health_df = pd.read_csv('/content/Big_Cities_Health_Data_Inventory.csv')
health_df.head()

,Indicator Category,Indicator,Year,Gender,Race/ Ethnicity,Value,Place
0,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2013,Both,All,30.4,"Atlanta (Fulton County), GA"
1,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2012,Both,All,39.6,"Atlanta (Fulton County), GA"
2,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,"Atlanta (Fulton County), GA"
3,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,"Atlanta (Fulton County), GA"
4,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Male,All,195.8,"Atlanta (Fulton County), GA"

In [ ]:
health_df.columns

Index(['Indicator Category', 'Indicator', 'Year', 'Gender', 'Race/ Ethnicity',
       'Value', 'Place'],
      dtype='object')

In [ ]:
health_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13509 entries, 0 to 13508
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Indicator Category  13509 non-null  object
 1   Indicator           13509 non-null  object
 2   Year                13509 non-null  object
 3   Gender              13509 non-null  object
 4   Race/ Ethnicity     13509 non-null  object
 5   Value               13496 non-null  float64
 6   Place               13509 non-null  object
dtypes: float64(1), object(6)
memory usage: 738.9+ KB

### Drop Rows with Missing Values
(Chose to drop rather than take the average because health data is sensitive and cost of measurement error is high)

In [ ]:
missing = health_df.isnull().sum()
missing.name = "Missing Count"
missing

Indicator Category     0
Indicator              0
Year                   0
Gender                 0
Race/ Ethnicity        0
Value                 13
Place                  0
Name: Missing Count, dtype: int64

In [ ]:
health_df.dropna(subset=['Value'], inplace=True)

In [ ]:
missing = health_df.isnull().sum()
missing.name = "Missing Count"
missing

Indicator Category    0
Indicator             0
Year                  0
Gender                0
Race/ Ethnicity       0
Value                 0
Place                 0
Name: Missing Count, dtype: int64

### Split Place into Three Columns

In [ ]:
health_df[['City', 'County', 'State']] = health_df['Place'].str.extract(
    r'^(.*?) \((.*?)\),\s*([A-Z]{2})$'
)
drop_cols = ['Place']
health_df = health_df.drop(columns=drop_cols)

In [ ]:
health_df.head()

,Indicator Category,Indicator,Year,Gender,Race/ Ethnicity,Value,City,County,State
0,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2013,Both,All,30.4,Atlanta,Fulton County,GA
1,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2012,Both,All,39.6,Atlanta,Fulton County,GA
2,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,Atlanta,Fulton County,GA
3,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,Atlanta,Fulton County,GA
4,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Male,All,195.8,Atlanta,Fulton County,GA

## 2: Climate Change Edit

In [ ]:
climate_df = pd.read_excel('/content/climate_change_edit.xls')
climate_df.head()

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [ ]:
climate_df.columns

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [ ]:
climate_df['Series name'].unique()

array(['Land area below 5m (% of land area)',
       'Agricultural land under irrigation (% of total ag. land)',
       'Cereal yield (kg per hectare)',
       'Foreign direct investment, net inflows (% of GDP)',
       'Access to electricity (% of total population)',
       'Energy use per units of GDP (kg oil eq./$1,000 of 2005 PPP $)',
       'Energy use per capita (kilograms of oil equivalent)',
       'CO2 emissions, total (KtCO2)',
       'CO2 emissions per capita (metric tons)',
       'CO2 emissions per units of GDP (kg/$1,000 of 2005 PPP $)',
       'Other GHG emissions, total (KtCO2e)',
       'Methane (CH4) emissions, total (KtCO2e)',
       'Nitrous oxide (N2O) emissions, total (KtCO2e)',
       'Disaster risk reduction progress score (1-5 scale; 5=best)',
       'GHG net emissions/removals by LUCF (MtCO2e)',
       'Droughts, floods, extreme temps (% pop. avg. 1990-2009)',
       'Population below 5m (% of total)',
       'Population in urban agglomerations >1million (%)',
       'Annual freshwater withdrawals (% of internal resources)',
       'Nationally terrestrial protected areas (% of total land area)',
       'Ease of doing business (ranking 1-183; 1=best)',
       'Invest. in energy w/ private participation ($)',
       'Invest. in telecoms w/ private participation ($)',
       'Invest. in transport w/ private participation ($)',
       'Invest. in water/sanit. w/ private participation ($)',
       'Public sector mgmt & institutions avg. (1-6 scale; 6=best)',
       'Paved roads (% of total roads)', 'GDP ($)',
       'GNI per capita (Atlas $)',
       'Ratio of girls to boys in primary & secondary school (%)',
       'Primary completion rate, total (% of relevant age group)',
       'Under-five mortality rate (per 1,000)',
       'Access to improved water source (% of total pop.)',
       'Nurses and midwives (per 1,000 people)',
       'Physicians (per 1,000 people)',
       'Malaria incidence rate (per 100,000 people)',
       'Access to improved sanitation (% of total pop.)',
       'Child malnutrition, underweight (% of under age 5)',
       'Population living below $1.25 a day (% of total)',
       'Population growth (annual %)', 'Population',
       'Urban population growth (annual %)', 'Urban population'],
      dtype=object)

### Check for Missing Values (None are Missing)

In [ ]:
missing = climate_df.isnull().sum()
missing.name = "Missing Count"
missing

Country code    0
Country name    0
Series code     0
Series name     0
SCALE           0
Decimals        0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
Name: Missing Count, dtype: int64

### Melting all the column headers which are years (values, not variable names)

In [ ]:
climate_tidy = climate_df.melt(
    id_vars=['Country code', 'Country name', 'Series code', 'Series name', 'SCALE', 'Decimals'],
    var_name='year',
    value_name='value'
)

In [ ]:
climate_tidy.head()

,Country code,Country name,Series code,Series name,SCALE,Decimals,year,value
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,1990,29.57481
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,1990,0
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,1990,0
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,1990,0.208235
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,1990,4.967875

### 4. Grades

In [76]:
grades = pd.read_csv("grades.csv")
grades.head()

   student_ID                    subject  year  autumn  winter  spring  summer
0           1             Basket-weaving  2023     110      38     107      31
1           2             Basket-weaving  2024      64      55      42     126
2           3  Underwater basket-weaving  2023      54      48      42      51
3           4  Underwater basket-weaving  2024      98     129     109     108
4           5             Basket-weaving  2023     121      62      75      59

In [77]:
grades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_ID  24 non-null     int64
 1   subject     24 non-null     object
 2   year        24 non-null     int64
 3   autumn      24 non-null     int64
 4   winter      24 non-null     int64
 5   spring      24 non-null     int64
 6   summer      24 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.4+ KB

In [78]:
grades.shape

(24, 7)

In [79]:
grades.columns

Index(['student_ID', 'subject', 'year', 'autumn', 'winter', 'spring',
       'summer'],
      dtype='object')

### Reshape the Data using melt

The dataset stores grades for different terms (`autumn`, `winter`, `spring`, `summer`) in separate columns.

In [80]:
grades_tidy = grades.melt(
    id_vars=["student_ID", "subject", "year"],
    value_vars=["autumn", "winter", "spring", "summer"],
    var_name="term",
    value_name="grade"
)

In [81]:
grades_tidy.isna().sum()

student_ID    0
subject       0
year          0
term          0
grade         0
dtype: int64

In [82]:
grades_tidy["grade"].describe()

count     96.000000
mean      79.593750
std       28.877446
min       31.000000
25%       54.750000
50%       79.000000
75%      108.250000
max      129.000000
Name: grade, dtype: float64

### Organize the Final Dataset

Sort the dataset by student, year, subject, and term to improve readability

In [83]:
grades_tidy

    student_ID                    subject  year    term  grade
0            1             Basket-weaving  2023  autumn    110
1            2             Basket-weaving  2024  autumn     64
2            3  Underwater basket-weaving  2023  autumn     54
3            4  Underwater basket-weaving  2024  autumn     98
4            5             Basket-weaving  2023  autumn    121
..         ...                        ...   ...     ...    ...
91           8              Boiling water  2024  summer    112
92           9              Boiling water  2023  summer     84
93          10                     Botany  2024  summer     74
94          11                     Botany  2023  summer     91
95          12                     Botany  2024  summer     81

[96 rows x 5 columns]

## 5. TB Dataset

### Load TB Dataset

Load the dataset and examine its structure to understand how the variables are stored.

In [84]:
tb = pd.read_csv("TB_notifications_LK_edit.csv")
tb.head()

,country,iso3,iso_numeric,whoregion and year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,Afghanistan,AFG,4,EMR -- 1980,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,4,EMR -- 1981,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,4,EMR -- 1982,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,4,EMR -- 1983,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,4,EMR -- 1984,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
tb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8492 entries, 0 to 8491
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             8492 non-null   object
 1   iso3                8492 non-null   object
 2   iso_numeric         8492 non-null   int64
 3   whoregion and year  8492 non-null   object
 4   new_sp              3902 non-null   float64
 5   new_sp_m04          1071 non-null   float64
 6   new_sp_m514         1082 non-null   float64
 7   new_sp_m014         3168 non-null   float64
 8   new_sp_m1524        3204 non-null   float64
 9   new_sp_m2534        3201 non-null   float64
 10  new_sp_m3544        3214 non-null   float64
 11  new_sp_m4554        3218 non-null   float64
 12  new_sp_m5564        3213 non-null   float64
 13  new_sp_m65          3204 non-null   float64
 14  new_sp_mu           915 non-null    float64
 15  new_sp_f04          1072 non-null   float64
 16  new_sp_f514         1085 non-null   float64
 17  new_sp_f014         3170 non-null   float64
 18  new_sp_f1524        3190 non-null   float64
 19  new_sp_f2534        3196 non-null   float64
 20  new_sp_f3544        3195 non-null   float64
 21  new_sp_f4554        3200 non-null   float64
 22  new_sp_f5564        3191 non-null   float64
 23  new_sp_f65          3193 non-null   float64
 24  new_sp_fu           913 non-null    float64
dtypes: float64(21), int64(1), object(3)
memory usage: 1.6+ MB

In [86]:
tb.shape

(8492, 25)

In [87]:
tb.columns

Index(['country', 'iso3', 'iso_numeric', 'whoregion and year', 'new_sp',
       'new_sp_m04', 'new_sp_m514', 'new_sp_m014', 'new_sp_m1524',
       'new_sp_m2534', 'new_sp_m3544', 'new_sp_m4554', 'new_sp_m5564',
       'new_sp_m65', 'new_sp_mu', 'new_sp_f04', 'new_sp_f514', 'new_sp_f014',
       'new_sp_f1524', 'new_sp_f2534', 'new_sp_f3544', 'new_sp_f4554',
       'new_sp_f5564', 'new_sp_f65', 'new_sp_fu'],
      dtype='object')

### Convert Data using melt

The dataset stores case counts in many columns where gender and age group are embedded in the column names. The dataset was reshaped into long format so that each row represents a single observation.

In [89]:
tb_tidy = tb.melt(
    id_vars=["country", "iso3", "iso_numeric", "whoregion and year"],
    var_name="case_type",
    value_name="cases"
)

In [90]:
tb_tidy = tb_tidy.dropna(subset=["cases"])

### Extract Gender and Age Group

The column names contain multiple variables (case type, gender, and age group). Extract these components into separate columns.

In [91]:
tb_tidy["gender"] = tb_tidy["case_type"].str.extract(r'_(m|f)')

In [92]:
tb_tidy["age_group"] = tb_tidy["case_type"].str.extract(r'(\d+)')

In [93]:
tb_tidy["case_category"] = tb_tidy["case_type"].str.extract(r'(new_[a-z]+)')

In [94]:
tb_tidy = tb_tidy.drop(columns=["case_type"])

In [95]:
tb_tidy = tb_tidy[
    ["country", "iso3", "iso_numeric", "whoregion and year",
     "case_category", "gender", "age_group", "cases"]
]

In [96]:
tb_tidy = tb_tidy.sort_values(
    ["country", "whoregion and year", "gender", "age_group"]
)

In [97]:
tb_tidy = tb_tidy.dropna(subset=["gender", "age_group"])

In [98]:
tb_tidy.isna().sum()

country               0
iso3                  0
iso_numeric           0
whoregion and year    0
case_category         0
gender                0
age_group             0
cases                 0
dtype: int64

In [99]:
tb_tidy

,country,iso3,iso_numeric,whoregion and year,case_category,gender,age_group,cases
110413,Afghanistan,AFG,4,EMR -- 1997,new_sp,f,014,5.0
118905,Afghanistan,AFG,4,EMR -- 1997,new_sp,f,1524,38.0
127397,Afghanistan,AFG,4,EMR -- 1997,new_sp,f,2534,36.0
135889,Afghanistan,AFG,4,EMR -- 1997,new_sp,f,3544,14.0
144381,Afghanistan,AFG,4,EMR -- 1997,new_sp,f,4554,8.0
...,...,...,...,...,...,...,...,...
56719,"occupied Palestinian territory, including east...",PSE,275,EMR -- 2012,new_sp,m,3544,1.0
65211,"occupied Palestinian territory, including east...",PSE,275,EMR -- 2012,new_sp,m,4554,2.0
22751,"occupied Palestinian territory, including east...",PSE,275,EMR -- 2012,new_sp,m,514,0.0
73703,"occupied Palestinian territory, including east...",PSE,275,EMR -- 2012,new_sp,m,5564,4.0
82195,"occupied Palestinian territory, including east...",PSE,275,EMR -- 2012,new_sp,m,65,2.0